-- k4inspector/fields.lua
-- This file defines all the protocol fields for the K4Direct dissector.

local fields = {}

fields.command = ProtoField.string("k4direct.command", "Command")
fields.vfo = ProtoField.string("k4direct.vfo", "VFO")
fields.full_message = ProtoField.string("k4direct.message", "Full Message")

-- IMPORTANT: Frequency field uses uint32 instead of uint64
-- ISSUE: ProtoField.uint64 causes Wireshark Lua API errors when calling TreeItem:add()
--        Error: "calling 'add' on bad self (userdata expected, got number)"
-- ROOT CAUSE: Wireshark's Lua API (as of v4.x) has issues with uint64 ProtoField types
--             in the 3-parameter form: subtree:add(field, buffer, value)
-- WORKAROUND: Use uint32 which works correctly with the Lua API
-- VALIDATION: uint32 max = 4,294,967,295 Hz = 4.2 GHz
--             K4 max frequency = 54 MHz (HF) or ~500 MHz (with XVTR)
--             uint32 is sufficient for all K4 use cases
-- TESTED: All real K4 captures parse correctly with uint32
fields.frequency = ProtoField.uint32("k4direct.frequency", "Frequency (Hz)", base.DEC)
fields.mode = ProtoField.uint8("k4direct.mode", "Mode", base.DEC)
fields.data_submode = ProtoField.uint8("k4direct.data_submode", "Data Sub-mode", base.DEC)
fields.rit_offset = ProtoField.int16("k4direct.rit_offset", "RIT Offset (Hz)", base.DEC)
fields.xit_offset = ProtoField.int16("k4direct.xit_offset", "XIT Offset (Hz)", base.DEC)
fields.rit_enabled = ProtoField.bool("k4direct.rit_enabled", "RIT Enabled")
fields.xit_enabled = ProtoField.bool("k4direct.xit_enabled", "XIT Enabled")
fields.split_enabled = ProtoField.bool("k4direct.split_enabled", "Split Enabled")
fields.tx_state = ProtoField.bool("k4direct.tx_state", "Transmitting")
fields.cw_speed = ProtoField.uint8("k4direct.cw_speed", "CW Speed (WPM)", base.DEC)
fields.cw_text = ProtoField.string("k4direct.cw_text", "CW Text")
fields.band_number = ProtoField.uint8("k4direct.band_number", "Band Number", base.DEC)
fields.filter_preset = ProtoField.uint8("k4direct.filter_preset", "Filter Preset", base.DEC)
fields.ai_level = ProtoField.uint8("k4direct.ai_level", "AI Level", base.DEC)
fields.radio_id = ProtoField.uint8("k4direct.radio_id", "Radio ID", base.DEC)
fields.active_vfo = ProtoField.string("k4direct.active_vfo", "Active VFO")
fields.scan_active = ProtoField.bool("k4direct.scan_active", "Scan Active")
fields.om_string = ProtoField.string("k4direct.om_string", "OM Option String")
fields.om_model = ProtoField.string("k4direct.om_model", "Radio Model")
fields.om_atu = ProtoField.bool("k4direct.om_atu", "ATU (KAT4)")
fields.om_pa = ProtoField.bool("k4direct.om_pa", "PA (KPA4)")
fields.om_xvtr = ProtoField.bool("k4direct.om_xvtr", "XVTR (Transverter)")
fields.om_subrx = ProtoField.bool("k4direct.om_subrx", "SUB RX (KRX4 + KDDC4)")
fields.om_hdr = ProtoField.bool("k4direct.om_hdr", "HDR MODULE (KHDR4 + KDDC4-2)")
fields.om_k40mini = ProtoField.bool("k4direct.om_k40mini", "K40 Mini")
fields.om_linear = ProtoField.bool("k4direct.om_linear", "Linear Amp")
fields.om_kpa1500 = ProtoField.bool("k4direct.om_kpa1500", "KPA1500 Amp")
fields.om_k4id = ProtoField.bool("k4direct.om_k4id", "K4 Identifier")
fields.power_output = ProtoField.uint16("k4direct.power_output", "Power Output (0.1W)", base.DEC)
fields.cw_pitch = ProtoField.uint16("k4direct.cw_pitch", "CW Pitch (Hz)", base.DEC)
fields.ag_gain = ProtoField.uint8("k4direct.ag_gain", "AF Gain", base.DEC)
fields.mg_gain = ProtoField.uint8("k4direct.mg_gain", "Mic Gain", base.DEC)
fields.rg_gain = ProtoField.uint8("k4direct.rg_gain", "RF Gain", base.DEC)
fields.cp_level = ProtoField.uint8("k4direct.cp_level", "Speech Compression", base.DEC)
fields.nb_level = ProtoField.uint8("k4direct.nb_level", "Noise Blanker", base.DEC)
fields.sm_reading = ProtoField.uint8("k4direct.sm_reading", "S-Meter", base.DEC)
fields.sq_level = ProtoField.uint8("k4direct.sq_level", "Squelch", base.DEC)
fields.agc_mode = ProtoField.uint8("k4direct.agc_mode", "AGC Mode", base.DEC)
fields.preamp = ProtoField.uint8("k4direct.preamp", "Preamp", base.DEC)
fields.attenuator = ProtoField.uint8("k4direct.attenuator", "Attenuator", base.DEC)
fields.bandwidth = ProtoField.uint16("k4direct.bandwidth", "Bandwidth (Hz)", base.DEC)
fields.antenna = ProtoField.uint8("k4direct.antenna", "Antenna", base.DEC)
fields.atu_status = ProtoField.uint8("k4direct.atu_status", "ATU Status", base.DEC)
fields.vfo_lock = ProtoField.bool("k4direct.vfo_lock", "VFO Lock")
fields.subrx_enabled = ProtoField.bool("k4direct.subrx_enabled", "Sub RX Enabled")
fields.spot_enabled = ProtoField.bool("k4direct.spot_enabled", "Spot Enabled")
fields.data_baud_rate = ProtoField.uint8("k4direct.data_baud_rate", "Data Baud Rate", base.DEC)
fields.menu_id = ProtoField.uint8("k4direct.menu_id", "Menu ID", base.DEC)
fields.menu_value = ProtoField.uint16("k4direct.menu_value", "Menu Value", base.DEC)
fields.power_control = ProtoField.uint16("k4direct.power_control", "Power Control", base.DEC)
fields.power_range = ProtoField.string("k4direct.power_range", "Power Range")
fields.eq_band_100 = ProtoField.int8("k4direct.eq_100", "100 Hz", base.DEC)
fields.eq_band_200 = ProtoField.int8("k4direct.eq_200", "200 Hz", base.DEC)
fields.eq_band_400 = ProtoField.int8("k4direct.eq_400", "400 Hz", base.DEC)
fields.eq_band_800 = ProtoField.int8("k4direct.eq_800", "800 Hz", base.DEC)
fields.eq_band_1200 = ProtoField.int8("k4direct.eq_1200", "1200 Hz", base.DEC)
fields.eq_band_1600 = ProtoField.int8("k4direct.eq_1600", "1600 Hz", base.DEC)
fields.eq_band_2400 = ProtoField.int8("k4direct.eq_2400", "2400 Hz", base.DEC)
fields.eq_band_3200 = ProtoField.int8("k4direct.eq_3200", "3200 Hz", base.DEC)
fields.vox_mode = ProtoField.string("k4direct.vox_mode", "VOX Mode")
fields.vox_state = ProtoField.bool("k4direct.vox_state", "VOX State")
fields.band_independence = ProtoField.bool("k4direct.band_independence", "Band Independence")
fields.diversity_mode = ProtoField.bool("k4direct.diversity_mode", "Diversity Mode")
fields.digout1 = ProtoField.bool("k4direct.digout1", "DIGOUT1")
fields.audio_effects = ProtoField.uint8("k4direct.audio_effects", "Audio Effects", base.DEC)
fields.auto_notch = ProtoField.bool("k4direct.auto_notch", "Auto Notch")
fields.tx_delay = ProtoField.uint16("k4direct.tx_delay", "TX Delay (10ms)", base.DEC)
fields.tx_gain = ProtoField.uint16("k4direct.tx_gain", "TX Gain", base.DEC)
fields.voice_input = ProtoField.uint8("k4direct.voice_input", "Voice Input Level", base.DEC)
fields.mic_input = ProtoField.uint8("k4direct.mic_input", "Mic Input", base.DEC)
fields.vfo_operation = ProtoField.uint8("k4direct.vfo_operation", "VFO Operation", base.DEC)
fields.if_center_freq = ProtoField.uint32("k4direct.if_center_freq", "IF Center Frequency (Hz)", base.DEC)
fields.if_shift = ProtoField.uint16("k4direct.if_shift", "IF Shift (x10 Hz)", base.DEC)
fields.essb_mode = ProtoField.uint8("k4direct.essb_mode", "ESSB Mode", base.DEC)
fields.essb_bandwidth = ProtoField.uint16("k4direct.essb_bandwidth", "ESSB Bandwidth (Hz)", base.DEC)
fields.vox_gain = ProtoField.uint8("k4direct.vox_gain", "VOX Gain", base.DEC)
fields.vox_gain_mode = ProtoField.string("k4direct.vox_gain_mode", "VOX Gain Mode")
fields.apf_mode = ProtoField.uint8("k4direct.apf_mode", "APF Mode", base.DEC)
fields.apf_bandwidth = ProtoField.uint8("k4direct.apf_bandwidth", "APF Bandwidth", base.DEC)

-- Batch 3: Complex structured commands
fields.qsk_full = ProtoField.bool("k4direct.qsk_full", "Full CW QSK")
fields.vox_delay_mode = ProtoField.string("k4direct.vox_delay_mode", "VOX Delay Mode")
fields.vox_delay = ProtoField.uint16("k4direct.vox_delay", "VOX/QSK Delay (10ms)", base.DEC)
fields.front_mic_preamp = ProtoField.uint8("k4direct.front_mic_preamp", "Front Mic Preamp (dB)", base.DEC)
fields.front_mic_bias = ProtoField.bool("k4direct.front_mic_bias", "Front Mic Bias")
fields.front_mic_controls = ProtoField.bool("k4direct.front_mic_controls", "Front Mic Controls")
fields.rear_mic_preamp = ProtoField.uint8("k4direct.rear_mic_preamp", "Rear Mic Preamp (dB)", base.DEC)
fields.rear_mic_bias = ProtoField.bool("k4direct.rear_mic_bias", "Rear Mic Bias")
fields.keyer_iambic_mode = ProtoField.string("k4direct.keyer_iambic_mode", "Keyer Iambic Mode")
fields.paddle_orientation = ProtoField.string("k4direct.paddle_orientation", "Paddle Orientation")
fields.keyer_weight = ProtoField.uint16("k4direct.keyer_weight", "Keyer Weight", base.DEC)
fields.line_out_left = ProtoField.uint8("k4direct.line_out_left", "Line Out Left Level", base.DEC)
fields.line_out_right = ProtoField.uint8("k4direct.line_out_right", "Line Out Right Level", base.DEC)
fields.line_out_mode = ProtoField.uint8("k4direct.line_out_mode", "Line Out Mode", base.DEC)
fields.line_in_usb = ProtoField.uint16("k4direct.line_in_usb", "Line In USB-B Level", base.DEC)
fields.line_in_line = ProtoField.uint16("k4direct.line_in_line", "Line In Jack Level", base.DEC)
fields.line_in_source = ProtoField.uint8("k4direct.line_in_source", "Line In Source", base.DEC)

-- Batch 4: Alternate format commands
fields.noise_blanker_level = ProtoField.uint8("k4direct.nb_level", "Noise Blanker Level", base.DEC)
fields.noise_blanker_state = ProtoField.bool("k4direct.nb_state", "Noise Blanker State")
fields.manual_notch_pitch = ProtoField.uint16("k4direct.nm_pitch", "Manual Notch Pitch (Hz)", base.DEC)
fields.manual_notch_state = ProtoField.bool("k4direct.nm_state", "Manual Notch State")
fields.noise_reduction_level = ProtoField.uint8("k4direct.nr_level", "Noise Reduction Level", base.DEC)
fields.noise_reduction_state = ProtoField.bool("k4direct.nr_state", "Noise Reduction State")
fields.preamp_type = ProtoField.uint8("k4direct.preamp_type", "Preamp Type", base.DEC)
fields.preamp_state = ProtoField.bool("k4direct.preamp_state", "Preamp State")
fields.pl_tone_number = ProtoField.uint8("k4direct.pl_tone", "PL Tone Number", base.DEC)
fields.pl_tone_state = ProtoField.bool("k4direct.pl_state", "PL Tone State")
fields.rx_atten_db = ProtoField.uint8("k4direct.rx_atten", "RX Attenuator (dB)", base.DEC)
fields.rx_atten_state = ProtoField.bool("k4direct.rx_atten_state", "RX Attenuator State")

return fields
